#!/bin/bash
# master-add-project.sh — 마스터 에이전트에 새 프로젝트 등록
# Generated by Claude Code for 24/7 autonomous development system
#
# 사용법:
#   master-add-project.sh <project-id> <project-dir> "<vision>"
#
# 예시:
#   master-add-project.sh myapp ~/projects/myapp "SaaS 앱. 유저 인증, 대시보드, 결제 기능 구현"

set -euo pipefail

ID="${1:-}"
DIR="${2:-}"
VISION="${3:-}"

if [ -z "$ID" ] || [ -z "$DIR" ] || [ -z "$VISION" ]; then
  echo "Usage: master-add-project.sh <id> <dir> \"<vision>\""
  exit 1
fi

MASTER_DIR="$HOME/.claude/master"
PROJECT_FILE="$MASTER_DIR/projects/${ID}.json"

if [ -f "$PROJECT_FILE" ]; then
  echo "Project already exists: $PROJECT_FILE"
  echo "Edit it directly to update vision or backlog."
  exit 1
fi

ABS_DIR=$(realpath "$DIR" 2>/dev/null || echo "$DIR")
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$PROJECT_FILE" << EOF
{
  "id": "$ID",
  "name": "$ID",
  "dir": "$ABS_DIR",
  "vision": "$VISION",
  "tech_stack": [],
  "priority": 1,
  "status": "active",
  "worker_session": null,
  "current_task": null,
  "backlog": [
    {
      "id": "task-001",
      "title": "프로젝트 초기 분석 및 계획",
      "description": "현재 코드베이스를 분석하고 비전 달성을 위한 구현 계획을 수립하세요. PLAN.md 파일에 정리해주세요.",
      "type": "chore",
      "priority": 1,
      "status": "pending",
      "created_at": "$NOW"
    }
  ],
  "done": [],
  "context_notes": "첫 번째 워커 실행 - 코드베이스 파악 후 backlog를 구체화할 것",
  "worker_config": {
    "model": "sonnet",
    "allowed_tools": ["Read", "Edit", "Write", "Bash", "Glob", "Grep"],
    "max_tokens_per_task": 50000
  }
}
EOF

echo "Project registered: $PROJECT_FILE"
echo ""
echo "Next steps:"
echo "  1. Edit the backlog in $PROJECT_FILE"
echo "  2. Run: bash ~/.claude/master/loop.sh status"
echo "  3. Start master if not running: ~/scripts/claude/master-start.sh start"
