#!/bin/bash
# master-start.sh — Master Agent tmux 세션 시작/재개
# Generated by Claude Code for 24/7 autonomous development system
#
# 사용법:
#   master-start.sh          # 마스터 세션 시작 (없으면 생성)
#   master-start.sh attach   # 기존 세션에 attach

MASTER_SESSION="master"
MASTER_LOOP="$HOME/.claude/master/loop.sh"

case "${1:-start}" in
  start)
    if tmux has-session -t "$MASTER_SESSION" 2>/dev/null; then
      echo "Master session already running. Attaching..."
      tmux attach -t "$MASTER_SESSION"
    else
      echo "Starting Master Agent session..."
      tmux new-session -d -s "$MASTER_SESSION" -x 220 -y 50
      tmux send-keys -t "$MASTER_SESSION" "bash $MASTER_LOOP start" Enter
      echo "Master session started. Attaching..."
      tmux attach -t "$MASTER_SESSION"
    fi
    ;;
  attach)
    tmux attach -t "$MASTER_SESSION" 2>/dev/null || echo "No master session running. Run: master-start.sh start"
    ;;
  stop)
    bash "$HOME/.claude/master/loop.sh" stop
    tmux kill-session -t "$MASTER_SESSION" 2>/dev/null || true
    echo "Master session stopped."
    ;;
  status)
    bash "$HOME/.claude/master/loop.sh" status
    ;;
  *)
    echo "Usage: master-start.sh {start|attach|stop|status}"
    ;;
esac
