#!/bin/bash
# vibe-coder.sh — 마스터 에이전트에서 워커 Claude 세션을 tmux로 제어
# Generated by Claude Code for master-agent vibe coding
#
# 사용법:
#   vibe-coder.sh start <session-name> <project-dir>  # 워커 시작
#   vibe-coder.sh send  <session-name> "<prompt>"      # 프롬프트 전송
#   vibe-coder.sh read  <session-name> [lines]         # 응답 읽기
#   vibe-coder.sh stop  <session-name>                 # 워커 종료
#   vibe-coder.sh list                                 # 활성 워커 목록

set -euo pipefail

CMD="${1:-}"
SESSION="${2:-}"

case "$CMD" in
  start)
    PROJECT_DIR="${3:-$PWD}"
    if tmux has-session -t "$SESSION" 2>/dev/null; then
      echo "이미 실행 중: $SESSION"
      exit 0
    fi
    tmux new-session -d -s "$SESSION" -x 220 -y 50
    tmux send-keys -t "$SESSION" "cd $PROJECT_DIR && cld" Enter
    echo "워커 시작됨: $SESSION ($PROJECT_DIR)"
    echo "초기화 대기 중..."
    sleep 6
    tmux capture-pane -t "$SESSION" -p | grep -E "Claude Code|❯" | head -3
    ;;

  send)
    PROMPT="${3:-}"
    if [ -z "$PROMPT" ]; then echo "프롬프트 필요"; exit 1; fi
    # 이전 신호 파일 제거 후 프롬프트 전송
    rm -f "/tmp/vibe-done-$SESSION"
    tmux send-keys -t "$SESSION" "$PROMPT" Enter
    ;;

  read)
    TIMEOUT="${3:-120}"  # 최대 대기 초 (기본 120초)
    SIGNAL="/tmp/vibe-done-$SESSION"
    ELAPSED=0
    # Stop hook이 신호 파일을 만들 때까지 0.2초 간격으로 폴링
    while [ ! -f "$SIGNAL" ]; do
      sleep 0.2
      ELAPSED=$((ELAPSED + 1))
      if [ $ELAPSED -ge $((TIMEOUT * 5)) ]; then
        echo "[timeout: ${TIMEOUT}s 초과]" >&2
        break
      fi
    done
    rm -f "$SIGNAL"

    # tail -r으로 뒤집어 마지막 빈 ❯(대기) ~ 직전 ❯ 질문 사이만 추출
    tmux capture-pane -t "$SESSION" -p -S -9999 \
      | tail -r \
      | awk '
          /^❯[[:space:]]*$/ && !started { started=1; next }
          /^❯ .+/           { if (started) exit }
          started            { print }
        ' \
      | tail -r \
      | grep -v "^[─━]\+$" \
      | grep -v "bypass permissions\|shift+tab\|ctrl+o" \
      | grep -v "📁\|💰\|🧠\|⏱\|🔥\|⏰\|⏳\|▐▛\|▝▜\|▘▘\|⎿" \
      | grep -v "Searched for\|read [0-9]\+ file\|Loaded " \
      | sed 's/^⏺ //' \
      | grep -v "^[[:space:]]*$"
    ;;

  stop)
    tmux send-keys -t "$SESSION" "/exit" Enter 2>/dev/null || true
    sleep 1
    tmux kill-session -t "$SESSION" 2>/dev/null || true
    echo "워커 종료: $SESSION"
    ;;

  list)
    echo "=== 활성 vibe-coder 워커 ==="
    tmux ls 2>/dev/null || echo "(없음)"
    ;;

  *)
    echo "사용법: vibe-coder.sh {start|send|read|stop|list} <session> [args]"
    exit 1
    ;;
esac
