[tools]
bun = "latest"
rust = "latest"
gh = "latest"
java = "zulu-javafx-17"
node = "24"
pnpm = "11.7.0"
python = "3.11"
redis = "latest"
uv = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
