#!/usr/bin/env python3
"""
Universal Editor Extension Cleaner - Generated by OpenCode Agent
Finds extension data in globalStorage for Cursor, VS Code, and other Electron editors
"""

import os
import json
import subprocess
from pathlib import Path
from typing import List, Dict, Set

# Supported editors configuration
EDITORS = {
    "cursor": {
        "name": "Cursor",
        "global_storage": Path.home()
        / "Library"
        / "Application Support"
        / "Cursor"
        / "User"
        / "globalStorage",
        "extensions_dir": Path.home() / ".cursor" / "extensions",
        "cli_command": ["cursor", "--list-extensions"],
    },
    "vscode": {
        "name": "VS Code",
        "global_storage": Path.home()
        / "Library"
        / "Application Support"
        / "Code"
        / "User"
        / "globalStorage",
        "extensions_dir": Path.home() / ".vscode" / "extensions",
        "cli_command": ["code", "--list-extensions"],
    },
    "vscodium": {
        "name": "VSCodium",
        "global_storage": Path.home()
        / "Library"
        / "Application Support"
        / "VSCodium"
        / "User"
        / "globalStorage",
        "extensions_dir": Path.home() / ".vscode-oss" / "extensions",
        "cli_command": ["codium", "--list-extensions"],
    },
    "cursor-insiders": {
        "name": "Cursor Insiders",
        "global_storage": Path.home()
        / "Library"
        / "Application Support"
        / "Cursor - Insiders"
        / "User"
        / "globalStorage",
        "extensions_dir": Path.home() / ".cursor-insiders" / "extensions",
        "cli_command": ["cursor-insiders", "--list-extensions"],
    },
}


def get_installed_extensions(editor_key: str) -> Set[str]:
    """Get list of installed extensions using editor CLI"""
    editor = EDITORS[editor_key]
    try:
        result = subprocess.run(
            editor["cli_command"], capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            extensions = [
                line.strip() for line in result.stdout.split("\n") if line.strip()
            ]
            return set(extensions)
    except Exception as e:
        pass  # CLI not available or failed
    return set()


def find_orphans(editor_key: str) -> List[Dict]:
    """Find extension orphans for a specific editor"""
    editor = EDITORS[editor_key]
    global_storage = editor["global_storage"]

    if not global_storage.exists():
        return []

    installed = get_installed_extensions(editor_key)
    orphans = []

    for item in global_storage.iterdir():
        if item.is_dir():
            ext_name = item.name
            if ext_name not in installed:
                size = sum(f.stat().st_size for f in item.rglob("*") if f.is_file())
                orphans.append(
                    {
                        "name": ext_name,
                        "path": str(item),
                        "size_mb": size / (1024 * 1024),
                        "editor": editor_key,
                    }
                )

    return orphans


def delete_orphans(orphans: List[Dict]) -> tuple:
    """Delete orphan extension data"""
    deleted = []
    failed = []

    for orphan in orphans:
        try:
            import shutil

            shutil.rmtree(orphan["path"])
            deleted.append(orphan)
            print(
                f"✅ Deleted: {orphan['name']} ({orphan['size_mb']:.2f} MB) [{orphan['editor']}]"
            )
        except Exception as e:
            failed.append((orphan, e))
            print(f"❌ Failed to delete {orphan['name']}: {e}")

    return deleted, failed


def main():
    print("🔍 Checking editor extension orphans...\n")

    all_orphans = []
    for editor_key in EDITORS.keys():
        editor = EDITORS[editor_key]
        if editor["global_storage"].exists():
            orphans = find_orphans(editor_key)
            if orphans:
                all_orphans.extend(orphans)

    if not all_orphans:
        print("✅ No orphans found!")
        return

    # Group by editor for display
    by_editor = {}
    total_size = 0
    for orphan in all_orphans:
        editor_key = orphan["editor"]
        if editor_key not in by_editor:
            by_editor[editor_key] = []
        by_editor[editor_key].append(orphan)
        total_size += orphan["size_mb"]

    print(f"Found {len(all_orphans)} orphan(s):\n")

    for editor_key, orphans in by_editor.items():
        editor_name = EDITORS[editor_key]["name"]
        print(f"📋 {editor_name}:")
        for orphan in orphans:
            print(f"   📁 {orphan['name']}")
            print(f"      Size: {orphan['size_mb']:.2f} MB")
        print()

    print(f"📊 Total: {total_size:.2f} MB")

    confirm = input("\n🗑️  Delete all orphans? (y/N): ").strip().lower()

    if confirm == "y":
        print("\nDeleting orphans...")
        deleted, failed = delete_orphans(all_orphans)

        if deleted:
            freed = sum(o["size_mb"] for o in deleted)
            print(f"\n✅ Deleted {len(deleted)} orphan(s)")
            print(f"📊 Total freed: {freed:.2f} MB")

        if failed:
            print(f"\n⚠️  Failed to delete {len(failed)} file(s)")
            for orphan, error in failed:
                print(f"   {orphan['name']}: {error}")
    else:
        print("\n❌ Cancelled")


if __name__ == "__main__":
    main()
